/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    From?: string;
                    To?: string;
                    IsCompleted?: boolean;
                    Search?: string;
                    SortBy?: components["schemas"]["SortBy"];
                    SortDir?: components["schemas"]["SortDir"];
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedResultOfTodoItem"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTodoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTodoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTodoRequest: {
            title: string;
            description: null | string;
            urgency?: components["schemas"]["UrgencyLevel"];
            /** Format: date-time */
            completeBy?: null | string;
        };
        PagedResultOfTodoItem: {
            items: components["schemas"]["TodoItem"][];
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            /** Format: int32 */
            pageNumber?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
        };
        /** @enum {unknown} */
        SortBy: "Date" | "Name" | "Status" | "Urgency";
        /** @enum {unknown} */
        SortDir: "Desc" | "Asc";
        TodoItem: {
            /** Format: int32 */
            id?: number | string;
            title: string;
            description?: null | string;
            isCompleted?: boolean;
            /** Format: date-time */
            createdAt?: string;
            urgency?: components["schemas"]["UrgencyLevel"];
            /** Format: date-time */
            completeBy?: null | string;
        };
        UpdateTodoRequest: {
            title: null | string;
            description: null | string;
            urgency: null | components["schemas"]["UrgencyLevel"];
            /** Format: date-time */
            completeBy: null | string;
            isCompleted: null | boolean;
        };
        /** @enum {unknown} */
        UrgencyLevel: "None" | "Low" | "Medium" | "High";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
